Repository TheAlgorithms/Algorithms-Explanation, pull requests merged in 2021-06, with the labels that each got.

#103 Add Indonesian Translation
  README.md
  id/README.md
Labels: enhancement, good first issue

#106 Counting Sort - English version
  en/Sorting Algorithms/Counting Sort.md
Labels: enhancement

#101 Finding Number of Digits in a Number
  en/Basic Math/Finding the number of digits in a number.md
Labels: approved, enhancement
