Repository TheAlgorithms/Algorithms-Explanation, pull requests merged in 2021-03, with the labels that each got.

#90 Fix longest common subsequence filename typo
  en/Dynamic Programming/Longest Common Subsequence.md
Labels: easy

#92 Exponential-Search Algorithm Explanation
  en/Search Algorithms/Exponential Search.md
Labels: approved, enhancement

#93 feat: Translate some explanations to Spanish
  es/Algoritmos de Ordenamiento/Ordenamiento Radix.md
  es/Algoritmos de Ordenamiento/Ordenamiento Shell.md
  es/Algoritmos de Ordenamiento/Ordenamiento de fusión.md
  es/Algoritmos de Ordenamiento/Ordenamiento de inserción.md
  es/Algoritmos de Ordenamiento/Ordenamiento de montón (heap sort).md
  es/Algoritmos de Ordenamiento/Ordenamiento de selección.md
  es/Algoritmos de Ordenamiento/Ordenamiento rapido.md
  es/Algoritmos de búsqueda/Búsqueda binaria.md
  es/Algoritmos de búsqueda/Búsqueda lineal.md
  es/Cifras/Cifrado Cesar.md
  es/Estructuras de datos/Gráfico/Bellman Ford.md
  es/Estructuras de datos/Listas vinculadas/Doble lista vinculada.md
  es/Estructuras de datos/Listas vinculadas/Lista singular vinculada.md
  es/Matematicas Básico/Numeros_Fibonacci.md
  es/Matematicas Básico/Promedio.md
  es/Procesamiento de imagenes/Detector de Harris.md
  es/Programación dinamica/Cambio de monedas.md
  es/Programación dinamica/Subsecuencia común más larga.md
Labels: enhancement, good first issue
