Repository TheAlgorithms/Algorithms-Explanation, pull requests merged in 2022-10, with the labels that each got.

#170 fix: broken cpp links
  en/Data Structures/Linked Lists/Doubly Linked List.md
  en/Data Structures/Linked Lists/Singly Linked List.md
  en/Search Algorithms/Binary Search.md
  en/Search Algorithms/Linear Search.md
  en/Selection Algorithms/Quick Select.md
  en/Sorting Algorithms/Quick Sort.md
  en/Sorting Algorithms/Selection Sort.md
  en/Sorting Algorithms/Shell Sort.md
Labels: easy, approved

#171 fixed brokenLink of C-Sharp
  en/Search Algorithms/Binary Search.md
  en/Sorting Algorithms/Shell Sort.md
  es/Algoritmos de Ordenamiento/Ordenamiento Burbuja.md
  es/Algoritmos de Ordenamiento/Ordenamiento Shell.md
  es/Algoritmos de búsqueda/Búsqueda binaria.md
  ko/정렬 알고리즘/셸 정렬.md
  ko/탐색 알고리즘/이진 탐색.md
  ko/탐색/이분탐색.md
  pt-br/Algoritmos de Busca/Busca Binaria.md
  pt-br/Algoritmos de Ordenação/Shell Sort.md
Labels: bug

#168 magic_square.md
  en/Basic Math/magic_square.md
Labels: enhancement

#182 fix: broken C repository links
  en/Search Algorithms/Binary Search.md
  en/Search Algorithms/Exponential Search.md
  en/Search Algorithms/Linear Search.md
  en/Sorting Algorithms/Quick Sort.md
  en/Sorting Algorithms/Selection Sort.md
  en/Sorting Algorithms/Shell Sort.md
Labels: bug

#178 Added RSA Algorithm Explainer
  en/Ciphers/rsa_cipher.md
Labels: enhancement

#181 Added Kadane's Algorithm Explanation and Walkthrough
  en/Dynamic Programming/Kadane's Algorithm.md
Labels: enhancement

#184 Added Stack Data Structures.md
  en/Data Structures/Stacks/stack.md
Labels: enhancement

#193 add Korean translation of quick select algorithm
  en/Selection Algorithms/Quick Select.md
  ko/선택 알고리즘/퀵 셀렉트.md
Labels: enhancement

#196 Add more Sorting Algorithms in French (Merge Sort, Selection Sort and Bubble Sort)
  fr/tri/Tri_fusion.md
  fr/tri/Tri_par_selection.md
  fr/tri/Tri_à_bulles.md
Labels: enhancement

#191 Update Playfair explanation
  en/Ciphers/playfair-cipher.md
Labels: enhancement

#198 Add Finding the Second Largest Element
  en/Selection Algorithms/Find Second Largest Element.md
Labels: enhancement
